(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g=this||self;function h(a,b){a=a.split(".");var c=g;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function k(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};function l(){}var m="function"==typeof Uint8Array;function n(a,b,c){a.c=null;b||(b=[]);a.i=void 0;a.f=-1;a.a=b;a:{if(b=a.a.length){--b;var d=a.a[b];if(!(null===d||"object"!=typeof d||Array.isArray(d)||m&&d instanceof Uint8Array)){a.g=b-a.f;a.b=d;break a}}a.g=Number.MAX_VALUE}a.h={};if(c)for(b=0;b<c.length;b++)d=c[b],d<a.g?(d+=a.f,a.a[d]=a.a[d]||p):(q(a),a.b[d]=a.b[d]||p)}var p=[];function q(a){var b=a.g+a.f;a.a[b]||(a.b=a.a[b]={})}
function r(a,b){if(b<a.g){b+=a.f;var c=a.a[b];return c===p?a.a[b]=[]:c}if(a.b)return c=a.b[b],c===p?a.b[b]=[]:c}function t(a,b){a=r(a,b);return null==a?a:!!a}function u(a){a=r(a,3);return null==a?0:a}function v(a,b){a=t(a,b);return null==a?!1:a}function w(a,b,c){b<a.g?a.a[b+a.f]=c:(q(a),a.b[b]=c)}function x(a,b,c,d){c!==d?w(a,b,c):b<a.g?a.a[b+a.f]=null:(q(a),delete a.b[b]);return a}function y(a,b,c){a.c||(a.c={});if(!a.c[c]){var d=r(a,c);d&&(a.c[c]=new b(d))}return a.c[c]}
function z(a,b,c){a.c||(a.c={});var d=c?c.a:c;a.c[b]=c;w(a,b,d)}function A(a,b){return new a(b?JSON.parse(b):null)}l.prototype.toString=function(){return this.a.toString()};function B(a){n(this,a,C)}k(B,l);var C=[17];function D(a){n(this,a,E)}k(D,l);var E=[8];function F(a){n(this,a,G)}k(F,l);var G=[27];function H(a){n(this,a,I)}k(H,l);var I=[1,2,3];function J(a){n(this,a,null)}k(J,l);function K(a){n(this,a,null)}k(K,l);function L(a){n(this,a,M)}k(L,l);var M=[13];function N(a){n(this,a,O)}k(N,l);var O=[8];function P(a){n(this,a,null)}k(P,l);function Q(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content");return""};function R(a,b){b=new CustomEvent(b);a.a.dispatchEvent(b)}function S(a){for(const b of a.a.querySelectorAll(".x-layout"))b.classList.add("mys-ad-shown")}
class aa{constructor(a,b){this.b=a;this.a=b;a=Q(b,"namespace");if(!a){a="ns-"+Math.random().toString(36).substr(2,5);a:{var c=b.getElementsByTagName("META");for(let d=0;d<c.length;++d)if("namespace"===c[d].getAttribute("name")){c[d].setAttribute("content",a);break a}c=document.createElement("META");c.setAttribute("name","namespace");c.setAttribute("content",a);b.appendChild(c)}}}};function T(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};function U(a){if(1>=a.b.offsetWidth||1>=a.b.offsetHeight)return!1;a.a.remove();R(a.c,"spanReady");return!0}
class ba{constructor(a,b){this.c=a;this.f=b;this.b=T("SPAN");this.b.style.fontSize="6px";this.b.textContent="go";this.a=T("DIV");this.a.style.position="absolute";this.a.style.top="100%";this.a.style.left="100%";this.a.style.width="1px";this.a.style.height="0";this.a.style.overflow="hidden";this.a.style.visibility="hidden";this.a.appendChild(this.b)}wait(){if(v(this.f,1))return null;R(this.c,"spanStart");this.c.a.appendChild(this.a);return U(this)?null:new Promise(a=>{const b=setInterval(()=>{U(this)&&
(clearInterval(b),a())},u(this.f))})}};function V(a){a.b&=-31}function W(a,b){a.b|=b}class ca{constructor(a,b){this.a=a;this.c=b;new P;this.b=0}f(){}};function X(a,b,c){if(b&&c){const d=y(a.a.c,L,6);x(d,2,b,0);x(d,3,c,0)}A(H,Q(a.b.a,"engine_msg")||"[]");return a.a.f()||Promise.resolve()}function da(a){V(a.a);W(a.a,1);window.AFMA_Communicator&&window.AFMA_Communicator.addEventListener("onshow",()=>{W(a.a,32);S(a.b)});let b=0;const c=a.b.a;c.addEventListener("browserRender",()=>{++b;if(1==b)R(a.b,"overallStart"),X(a).then(()=>{R(a.b,"overallQuiet")});else{var d=c.clientWidth,f=c.clientHeight;d&&f&&X(a,d,f)}})}
class ea{constructor(a,b,c,d){this.b=new aa(a,b);a=new N(c);this.a=d(this.b,a)}};function fa(a){a.c.length=0;a.b=!0}function Y(a,b=null){a.a=!0;const c=()=>{a.b=!1;const d=a.c.shift();return void 0===d?(a.a=!1,Promise.resolve()):Y(a,d())};return b?b.then(c,()=>{if(a.b)return c();a.a=!1;return Promise.reject()}):c()}function ha(a,b){for(const c of b)a.c.push(c);return a.a?null:Y(a)}class ia{constructor(){this.b=this.a=!1;this.c=[]}};function ja(a){R(a.a,"browserReady");R(a.a,"browserReadyEnd");W(a,4);0!=(a.b&32)&&S(a.a);"complete"===document.readyState?Z(a):window.addEventListener("load",()=>{Z(a)});R(a.a,"overallReady");return null}
function Z(a){a=a.a.b;const b=a.ownerDocument;var c=a.querySelectorAll("meta[x-phase]");for(const d of c)c=b.createElement("STYLE"),c.setAttribute("x-phase",d.getAttribute("x-phase")),c.setAttribute("x-layout",d.getAttribute("x-layout")),c.appendChild(b.createTextNode(d.getAttribute("x-css"))),a.appendChild(c),d.remove()}
class ka extends ca{constructor(a,b){super(a,b);this.g=new ia}f(){fa(this.g);return ha(this.g,[()=>null,()=>{{var a=null;const b=y(y(this.c,L,6),K,1);b&&(a=(new ba(this.a,b)).wait());R(this.a,"browserStart");R(this.a,"browserStartEnd");V(this);W(this,2)}return a},()=>ja(this),()=>{R(this.a,"browserQuiet");R(this.a,"browserQuietEnd");W(this,8);return null}])}}
(function(a){let b=null;h("mys.engine.init",(c,d)=>{const f=A(N,Q(d,"render_config")||"[]");b=new ea(c,d,f.a,a);da(b)});h("mys.engine.stage",()=>b?b.a.b:0)})(function(a,b){if(null!=r(b,6))var c=y(b,L,6);else{c=y(b,F,1);var d=y(b,D,12)||new D;var f=new L;var e=t(d,6)||!1;f=x(f,10,e,!1);e=r(d,2)||0;f=x(f,7,e,0);e=t(d,16)||!1;f=x(f,19,e,!1);e=t(d,15)||!1;f=x(f,18,e,!1);e=new K;e=x(e,3,100,0);e=x(e,4,1E4,0);t(d,4)?(x(e,6,!0,!1),x(e,7,"monospace",""),x(e,8,"IMWimw0.!?@","")):(t(d,5)&&x(e,9,!0,!1),x(e,
5,!0,!1));z(f,1,e);e=new J;y(c,B,10)&&v(y(c,B,10),6)&&x(e,1,!0,!1);v(c,16)&&!t(d,1)&&x(e,2,!0,!1);z(f,4,e);c=f}z(b,6,c);return new ka(a,b)});}).call(this);
